### ISSUE TITLE
Need help with usage

### ISSUE THREAD

**Issue by bwareham** [jonasundderwolf/django-admin-locking#4]
I'm trying to incorporate this package in a project, but it's not preventing two people from editing the same item simultaneously. I suspect I'm not using the AdminLockingMixin correctly.

I have admin_locking installed:

```
INSTALLED_APPS = [
    'users.apps.UsersConfig', # custom user model
    'items.apps.ItemsConfig',
    'plans.apps.PlansConfig',
    'grappelli',
    'admin_locking',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
```
Admin looks like this:

```
class ItemAdmin(admin_locking.AdminLockingMixin, admin.ModelAdmin):
\...
admin.site.register(Item, ItemAdmin)
```

I'm using Django 3.1, which has caused some url issues for me elsewhere. So in admin.py I tried replacing:

`from django.conf.urls import url`

with

`from django.urls import re_path`

and

```
    def get_urls(self):
        return [
            url(r'^(.+)/locking/$', self.admin_site.admin_view(self.locking)),
        ] + super().get_urls()
```
with
```
    def get_urls(self):
        return [
            re_path(r'^(.+)/locking/$', self.admin_site.admin_view(self.locking)),
        ] + super().get_urls()
```
That didn't provide a fix, so I'm back to thinking I don't understand how to use the mixin.

**Comment by jhrdt** [comment]
Hi @bwareham,

**System: Python 3.8.10 and Django 3.2.8**

I got a workaround for this.

**1** - I copied the app into my Django project (no install via pip)

**2** - I added jquery to the media class of my admin model (demo class Habitat)

```
@admin.register(Habitat)
class HabitatAdmin(admin_locking.AdminLockingMixin, admin.ModelAdmin):
    list_display = [
        'name',
        'updated_at',
        'created_at'
    ]

    class Media:
        js = (
            'https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js',
            'admin_locking/admin_locking.js',
        )
```

_Note: This is a fast fix, there are options to add js files to the present js variable (extending). This approach overrides the js variable from the AdminLockingMixin._

**3** -  I edited the _admin_locking.js_ file:

I changed

```
    $(window).unload(clear_lock);
```

to

```
    $(window).on('unload', (e) = {
      clear_lock
    });
```

This has to do with jQuery 3.6.0.

**Comment by MRigal** [comment]
Hi @bwareham and thanks @jhrdt for the work-around.

We have indeed an issue on Django 3.2 that we also notified recently. Since the package became less in-use at our company, we hadn't noticed. We plan to release a fix soon. If you want, feel free to submit a PR with the fix (may I suggest to use the django builtin jquery?) and we'll be glad to merge it.

**Comment by jhrdt** [comment]
Hi @MRigal ,

I will prepare a PR.
